<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <Version>0.3.0</Version>
    <Authors>Team Wong</Authors>
    <Product>voiceling</Product>
    <Copyright>Copyright © Team Wong. Apache-2.0.</Copyright>
  </PropertyGroup>
</Project>
